name: Snapshot build

on:
  push:
    branches-ignore:
      - 'release-**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - uses: ./.github/actions/configure
        with:
          gpg-secret-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg-keyid-last8: ${{ secrets.OSSRH_GPG_KEY_ID_LAST_8 }}
          gpg-secret-passphrase: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSPHRASE }}

      - uses: ./.github/actions/version
        id: version

      - name: Debug environment set from above
        run: |
          echo "BETA_VERSION = $BETA_VERSION"
          echo "UXKIT_SUFFIX = $UXKIT_SUFFIX"
          echo "UXKIT_VERSION = $UXKIT_VERSION"
          echo "UXKIT_CONFIGURED = $UXKIT_CONFIGURED"
          echo "VERSION_CONFIGURED = $VERSION_CONFIGURED"

      - name: Build and Install
        id: build
        run: |
          ./gradlew -PUXKIT_SUFFIX=$UXKIT_SUFFIX :assembleAll :app:assembleDebug :installAll
          mkdir -p ./repository
          cp -r ~/.m2/repository/* ./repository
          zip -r repository.zip ./repository

      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: repository
          path: repository.zip

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - uses: ./.github/actions/configure
        with:
          gpg-secret-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg-keyid-last8: ${{ secrets.OSSRH_GPG_KEY_ID_LAST_8 }}
          gpg-secret-passphrase: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSPHRASE }}

      - uses: ./.github/actions/version
        id: version
      
      - name: Check mandatory variables
        id: check
        run: |
          echo "${{ steps.version.outputs.uxkit }}"

      - name: Create release
        if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/beta/') }}
        run: |
          echo "sonatypeUsername=${{ secrets.OSSRH_USERNAME }}" >> gradle.properties
          echo "sonatypePassword=${{ secrets.OSSRH_PASSWORD }}" >> gradle.properties
          export branch="${{ github.ref }}"
          ./gradlew -PUXKIT_SUFFIX=$UXKIT_SUFFIX :assembleAll
          ./gradlew -PUXKIT_SUFFIX=$UXKIT_SUFFIX publishToSonatype closeAndReleaseStagingRepository

      - name: Create Github's beta release
        id: automatic_beta
        if: startsWith(github.ref, 'refs/heads/beta/')
        uses: "./.github/actions/action-automatic-releases-1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v${{ steps.version.outputs.uxkit }}"
          prerelease: true
          title: ${{ steps.version.outputs.uxkit }}

      - name: Create Github's main release
        id: automatic_main
        if: github.ref == 'refs/heads/main'
        uses: "./.github/actions/action-automatic-releases-1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v${{ steps.version.outputs.uxkit }}"
          prerelease: false
          title: ${{ steps.version.outputs.uxkit }}
