name: Snapshot build

on:
  push:
    branches-ignore:
      - 'master'
      - 'release-**'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Run tests
        id: codeartifact_login
        run: bash ./scripts/tests.sh

      - name: Unit Tests Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: ./**/build/test-results/**/*.xml

      - name: Add coverage to PR
        id: jacoco
        uses: codlab/jacoco-report@v1.2.3
        with:
          paths: ./app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml,./uxkit/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml,./uxkit-common/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml,./uxkit-exoplayer-support/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml,./uxkit-firebase/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml,./uxkit-incoming-call/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml,./uxkit-screenshare/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml,./uxkit-self-managed-call/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml,./uxkit-system-service/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml,./uxkit-youtube/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          debug-mode: true
          fail-on-read: false
          min-coverage-overall: 0
          min-coverage-changed-files: 0

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.CODEARTIFACT_REGION }}


      - name: Prepare wrapper environment
        id: codeartifact_login
        run: |
          CODEARTIFACT_TOKEN=$(/usr/local/bin/aws codeartifact get-authorization-token --duration-seconds 900 --domain ${{ secrets.CODEARTIFACT_DOMAIN }} --domain-owner ${{ secrets.CODEARTIFACT_DOMAIN_OWNER }} --region ${{ secrets.CODEARTIFACT_REGION }} --output text --query authorizationToken)
          echo "::add-mask::$CODEARTIFACT_TOKEN"
          echo "CODEARTIFACT_TOKEN=$CODEARTIFACT_TOKEN" >> $GITHUB_ENV


      - name: Check build for master
        id: master_configuration
        if: github.ref == 'refs/heads/master'
        run: |
          echo "building for master... nothing to do, the version will be used"


      - name: Check build for beta
        id: beta_configuration
        if: startsWith(github.ref, 'refs/heads/beta/')
        run: |
          echo "building for beta..."
          export message="${{ github.event.head_commit.message }}"
          if [[ "$message" =~ (beta\.[[:digit:]]+) ]]; then
            export BETA_VERSION="${BASH_REMATCH[1]}"
            echo "UXKIT_SUFFIX=$BETA_VERSION" >> $GITHUB_ENV
          else
            echo "no beta.X pattern found in the commit generating this pipeline. Please update and retrigger a build"
            exit 1
          fi


      - name: Configure specific environment information
        id: environment
        run: |
          grep "version=" uxkit.gradle | cut -d'=' -f2 | sed "s/[^[:digit:][:alpha:]\.-]//g"
          export VERSION=$(grep "version=" uxkit.gradle | cut -d'=' -f2 | sed "s/[^[:digit:][:alpha:]\.-]//g")
          # replaces the VERSION with "version-suffix"
          [ ! -z "$UXKIT_SUFFIX" ] && export VERSION=$VERSION-$UXKIT_SUFFIX
          echo "will build $VERSION"
          echo "::set-output name=version::v$VERSION"


      - name: Build and Install
        id: build
        run: |
          ./gradlew -PUXKIT_SUFFIX=$UXKIT_SUFFIX :assembleAll :app:assembleDebug :installAll
          mkdir -p ./repository
          cp -r ~/.m2/repository/* ./repository
          zip -r repository.zip ./repository


      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: repository
          path: repository.zip


      - name: Create release
        if: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/beta/') }}
        run: |
          export branch="${{ github.ref }}"
          if [[ "$branch" == "master" ]]; then
            /usr/local/bin/aws s3 sync ~/.m2/repository/ "$ARTIFACT_REPO_URL_MASTER" --acl "public-read"
          else
            /usr/local/bin/aws s3 sync ~/.m2/repository/ "$ARTIFACT_REPO_URL_BETA" --acl "public-read"
          fi
        env:
          ARTIFACT_REPO_URL_MASTER: ${{ secrets.ARTIFACT_REPO_URL_MASTER }}
          ARTIFACT_REPO_URL_BETA: ${{ secrets.ARTIFACT_REPO_URL_BETA }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.CODEARTIFACT_REGION }}


      - name: Create tag
        if: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/beta/') }}
        uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ steps.environment.outputs.version }}


      - name: Create Github's beta release
        id: automatic_beta
        if: startsWith(github.ref, 'refs/heads/beta/')
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.environment.outputs.version }}
          prerelease: true
          title: ${{ steps.environment.outputs.version }}
          files: |
            repository.zip


      - name: Create Github's master release
        id: automatic_master
        if: github.ref == 'refs/heads/master'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.environment.outputs.version }}
          prerelease: false
          title: ${{ steps.environment.outputs.version }}
          files: |
            repository.zip
