name: Snapshot build

on:
  push:
    branches-ignore:
      - 'master'
      - 'release-**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.CODEARTIFACT_REGION }}


      - name: Login to CodeArtifact
        id: codeartifact_login
        run: |
          CODEARTIFACT_TOKEN=$(/usr/local/bin/aws codeartifact get-authorization-token --duration-seconds 900 --domain ${{ secrets.CODEARTIFACT_DOMAIN }} --domain-owner ${{ secrets.CODEARTIFACT_DOMAIN_OWNER }} --region ${{ secrets.CODEARTIFACT_REGION }} --output text --query authorizationToken)
          echo "::add-mask::$CODEARTIFACT_TOKEN"
          echo "CODEARTIFACT_TOKEN=$CODEARTIFACT_TOKEN" >> $GITHUB_ENV


      - name: Check build for master
        id: master_configuration
        if: github.ref == 'refs/heads/master'
        run: |
          echo "building for master... nothing to do, the version will be used"


      - name: Check build for beta
        id: beta_configuration
        if: startsWith(github.ref, 'refs/heads/beta/')
        run: |
          echo "building for beta..."
          export message="${{ github.event.head_commit.message }}"
          if [[ "$message" =~ (beta\.[[:digit:]]+) ]]; then
            export BETA_VERSION="${BASH_REMATCH[1]}"
            echo "UXKIT_SUFFIX=$BETA_VERSION" >> $GITHUB_ENV
          else
            echo "no beta.X pattern found in the commit generating this pipeline. Please update and retrigger a build"
            exit 1
          fi


      - name: Configure specific environment information
        id: environment
        run: |
          grep "version=" uxkit.gradle | cut -d'=' -f2 | sed "s/[^[:digit:][:alpha:]\.-]//g"
          export VERSION=$(grep "version=" uxkit.gradle | cut -d'=' -f2 | sed "s/[^[:digit:][:alpha:]\.-]//g")
          # replaces the VERSION with "version-suffix"
          [ ! -z "$UXKIT_SUFFIX" ] && export VERSION=$VERSION-$UXKIT_SUFFIX
          echo "will build $VERSION"
          echo "::set-output name=version::v$VERSION"


      - name: Build and Install
        id: build
        run: |
          ./gradlew -PUXKIT_SUFFIX=$UXKIT_SUFFIX :assembleAll :app:assembleDebug :installAll
          mkdir artifacts
          cp -r ~/.m2/repository ./artifacts/


      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: assets-for-download
          path: artifacts


      - name: Create release
        if: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/beta/') }}
        run: |
          export branch="${{ github.ref }}"
          if [[ "$branch" == "master" ]]; then
            /usr/local/bin/aws s3 sync ~/.m2/repository/ "${ARTIFACT_REPO_URL_MASTER}/release/" --acl "public-read"
          else
            /usr/local/bin/aws s3 sync ~/.m2/repository/ "${ARTIFACT_REPO_URL_BETA}/release/" --acl "public-read"
          fi


      - name: Create tag
        if: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/beta/') }}
        uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ steps.environment.outputs.version }}

